name: 'DITA-OT Build Action'
description: 'Build DITA-OT Artifacts'
inputs:
  dita-ot-version:
    description: 'The version of DITA-OT to use'
    required: false
    default: '3.6'
  prerequisites:
    description: 'Comma separated list of additional DITA-OT plugins to install.'
    required: false
  setup-script:
    description: 'A bash script to run to install any other runtime dependencies'
    required: false
    default: 'setup.sh'
  ditamap:
    description: 'The location of the ditamap to use'
    required: false
    default: 'document.ditamap'
  transtypes:
    description: 'Comma separated list of transforms to run'
    default: 'pdf'
    required: false
  properties:
    description: 'Additional properties to input'
    default: ''
    required: false
  output-dir:
    description: 'Location for the DITA-OT build outputs'
    default: 'out'
    required: false
branding:
  icon: 'book-open'  
  color: 'blue'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.dita-ot-version }}
    - ${{ inputs.prerequisites }}
    - ${{ inputs.setup-script }}
    - ${{ inputs.ditamap }}
    - ${{ inputs.transtypes }}
    - ${{ inputs.properties }}
    - ${{ inputs.output-dir }}
