name: 'DITA-OT Build Action'
description: 'Build DITA-OT Artifacts'
inputs:
  transtype:
    description: 'transform to run'
    required: false
  input:
    description: 'The location of the ditamap to use'
    required: false
    default: 'document.ditamap'
  output-path:
    description: 'Location for the DITA-OT build outputs'
    default: 'out'
    required: false
  properties:
    description: 'Additional properties to input'
    default: ''
    required: false
  plugins:
    description: 'Comma separated list of additional DITA-OT plugins to install.'
    required: false
  install:
    description: 'Command-line input or a bash script to run to install plugins or any other runtime dependencies'
    required: false
  build:
    description: 'Command-line input or a bash script to run the DITA-OT Build'
    required: false
  dita-ot-version:
    description: 'The version of DITA-OT to use'
    required: false
    default: '3.6'
branding:
  icon: 'book-open'  
  color: 'blue'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.transtype }}
    - ${{ inputs.input }}
    - ${{ inputs.output-path }}
    - ${{ inputs.properties }}
    - ${{ inputs.plugins }}
    - ${{ inputs.install }}
    - ${{ inputs.build }}
    - ${{ inputs.dita-ot-version }}
